version: '3.9'

services:
  db_test:
    image: postgres:15-alpine
    container_name: payments-pg-test
    restart: unless-stopped
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: payment_processor_test
    ports:
      - '5433:5432'
    volumes:
      - payments_pgdata_test:/var/lib/postgresql/data
      - ./docker/postgres/init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U "app" -d "payments_test"']
      interval: 10s
      timeout: 3s
      retries: 10

volumes:
  payments_pgdata_test:
