version: '3.9'

services:
  db:
    image: postgres:15-alpine
    container_name: payments-pg
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-app}
      POSTGRES_DB: ${POSTGRES_DB:-payments}
    ports:
      - '5432:5432'
    volumes:
      - payments_pgdata:/var/lib/postgresql/data
      - ./docker/postgres/init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U "$$POSTGRES_USER" -d "$$POSTGRES_DB"']
      interval: 10s
      timeout: 3s
      retries: 10
    logging:
      options:
        max-size: '10m'
        max-file: '3'

volumes:
  payments_pgdata:
